---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: go-pmtud
rules:
- apiGroups:
  - pmtud.cloud.sap
  resources:
  - pmtunoderelays
  verbs:
  - create
  - delete
  - get
  - list
  - watch
