//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PMTUNodeRelay) DeepCopyInto(out *PMTUNodeRelay) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PMTUNodeRelay.
func (in *PMTUNodeRelay) DeepCopy() *PMTUNodeRelay {
	if in == nil {
		return nil
	}
	out := new(PMTUNodeRelay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PMTUNodeRelay) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PMTUNodeRelayList) DeepCopyInto(out *PMTUNodeRelayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PMTUNodeRelay, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PMTUNodeRelayList.
func (in *PMTUNodeRelayList) DeepCopy() *PMTUNodeRelayList {
	if in == nil {
		return nil
	}
	out := new(PMTUNodeRelayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PMTUNodeRelayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PMTUNodeRelaySpec) DeepCopyInto(out *PMTUNodeRelaySpec) {
	*out = *in
	in.ExpiresAt.DeepCopyInto(&out.ExpiresAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PMTUNodeRelaySpec.
func (in *PMTUNodeRelaySpec) DeepCopy() *PMTUNodeRelaySpec {
	if in == nil {
		return nil
	}
	out := new(PMTUNodeRelaySpec)
	in.DeepCopyInto(out)
	return out
}
