# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-pmtud
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: go-pmtud
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: go-pmtud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: go-pmtud
subjects:
  - kind: ServiceAccount
    name: go-pmtud
    namespace: kube-system
